language: java
jdk:
- oraclejdk8
script:
- mvn verify
after_success:
- mvn coveralls:report
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings travis/settings.xml
cache:
  directories:
  - "~/.m2"
branches:
  only:
  - master
  - "/^bullet-service-[0-9]+\\.[0-9]+\\.[0-9]+/"
env:
  global:
  - secure: QIYk6xLHlCSnpFRfLq/0w5lhsP1otV5AOhjX+fcxByjTEm2dNjywEpPDJbhgEXrCyiSVDXGlUnV+EcD0BdoT+CQ0eYYWqceSigKq5W/ucNIdL0LIvNENajSns/6DYLOJuLaDDCBYWfZar2nGG3i8v1repYV+OfVTTfGt6Of8+vgL9npXpvRf5mfzYMQijB8AQNat9OSQkAdWxZYamUgSNOj7bxlHI6aW8KuFDIxpMeQGKNiLqacbSsHJl5STVIzyPmt4FKzO8aVnOj0bmwI3ZeaaD+Fny2U0/4/mQ/P/5xwNyjU3WwjE8dcahY5WT4Rc3hu+I96wuqli58ffv1J0Rn0TJhyUyG+KbVw1rezx0POovkeIn6L22v/7dBnux3xSjbDW4adNFWR5U6ZJn9D7xwLaMPuKEhe0B5lZnu+OT6w66ISd4z8UeXjL0Cqh51y+6sY8Sul5jNBsp49mighYmqlIrkMI4HB4bu96PClJBKPatIT8av5HzCwKMK6xZcIl6C1I48rSb4UXiBxoTEQH/mcRcnSxbeWhWquqKOKa3p4VVWN3IVpckGWk3lSC/EmQuhGt6/7kz1Ixl1Gt2cAG7dC/npEXyCMGXYZHAP7TOIEIHWSRpkTAmoLhlgJFwCmAy6yMo8RttZYRtHoD4LDRz7RyR8kKeQT1birfM3apLgg=
  - secure: jFHWjHfc7BQmwyMQ1fcLSPo/Q26anZFz1uoGNQGoY8R/7xxPWsTbwYdbbYM//V6hym/pW6729mlbd2nNFSC7CsuQEJ+IzNvUVwhV/+zxneEVJhKNEmQMDWldkvJujUiD8VKM8M0lIyfdHK20iingMYzkWS4WZruCrJ1bznecEnM16ikIXrMbq1c8jaQK/ZxlxSwP9eVa7CToa3y8FFPOnPfFk1b1DW5tf4iDv2k/3j+vwXqfwBo+AXrDvjZFPCe2Q7McH8l/iQoelpXrA2nnX8nyoa3WCFSn/B8w/bnwPp0dqwJIv+9R0kVhKfN9KS2jFmJgp/4X2qYITPrgL7Oe+VsJkqXTdciohQFnkxqNkBH1Ri+MxCW6i26oEpzDR4+1mF19CNNmD58TLDBd2LanHJQaIn7Sa832SE4t+LYVnwWZhzo/zsdY77uyCSaIT3sUaObno7C/DRCT+kI4g9cWPvAvYbUh3mrTciI7Xy1Pj7naE34T/dV7lx+sav0iHk52GFG1ZEI/PRDxhbaVk8sUbwYNPjp4ACigZzaIfoMz3qmIKibk+D8cpwxnZlsMc2ZoZ1V6+WxvVoim6WP/fu/fg9pRWhgPBNDLb0bPHs8UhHqokCHx1xuqssIDj+XeLjyfYJLpkRUuI7E7doEkAocBHxE+RBCl2oJqdNx56gaOKg8=
